# Generated by Django 5.0.1 on 2024-02-05 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dc', '0002_dc_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dc',
            name='city',
        ),
    ]
